services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - backend
