services:
  frontend:
    build:
      context: ./frontend
      target: base
    command: npm start
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 3000:3000
