services:
  database:
    container_name: database
    image: mongo
    volumes:
      - database-volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80

volumes:
  database-volume: