name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  # Verify that the frontend builds
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
    
  # frontend-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v2
  #     - name: Install dependencies
  #       run: npm install
